name: Gemini AI Code Review

on:
  issue_comment:
    types: [created]

permissions:
  write-all

jobs:
  gemini-code-review:
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '/gemini review')

    steps:
      - name: Check PR Target Branch
        id: check-target
        run: |
          PR_JSON=$(gh api repos/${{ github.repository }}/pulls/${{ github.event.issue.number }})
          BASE_BRANCH=$(echo $PR_JSON | jq -r .base.ref)
          if [ "$BASE_BRANCH" != "main" ]; then
            echo "This PR is not targeting main branch (targeting: $BASE_BRANCH). Skipping review."
            exit 78
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB }}

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get PR Details
        id: pr
        run: |
          PR_JSON=$(gh api repos/${{ github.repository }}/pulls/${{ github.event.issue.number }})
          echo "head_sha=$(echo $PR_JSON | jq -r .head.sha)" >> $GITHUB_OUTPUT
          echo "base_sha=$(echo $PR_JSON | jq -r .base.sha)" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB }}